[build]
  command = 'echo -e "\ngoogleAnalytics: $GOOGLE_ANALYTICS \n" >> config.yaml && hugo --gc --minify'
  publish = "public"
  ignoreErrors = ["error-remote-getjson"]

[build.environment]
  HUGO_VERSION = "0.92.0"

